trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: build_and_deploy_blazor_app
    displayName: 'Build blazor app and deploy it'
    jobs:
    - job: build_and_deploy
      steps:
      - script: dotnet build --configuration $(buildConfiguration) src/Blazor.App/BlazorApp.csproj
        displayName: 'Building $(buildConfiguration)...'