# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-16.04

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- script: dotnet restore src/TaxCalculator.WebApi/TaxCalculator.WebApi.csproj
  displayName: 'dotnet restore'

- script: dotnet build src/TaxCalculator.WebApi/TaxCalculator.WebApi.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'  