trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: build_and_deploy_blazor_app
    displayName: 'Build blazor app and deploy it'