# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webProject: 'src/TaxCalculator.WebApi/TaxCalculator.WebApi.csproj'

stages:
- stage: build_and_deploy_webapi
  displayName: 'Build web api and deploy image to docker hub'
  jobs:
  - job: build_and_deploy
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        buildContext: $(Build.SourcesDirectory)/src
        repository: 'malagueta/pensiontools'
        dockerfile: 'src/TaxCalculator.WebApi/Dockerfile'
        containerRegistry: 'kDocker Registery'
        tags: |
          0.0.$(Build.BuildId)
          latest
- stage: buid_and_deploy_ui
  displayName: 'Build and deploy vue ui'
  jobs:
  - job: build_and_deploy
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - task: CmdLine@2
        inputs:
          script: 'cd src/vue.app.ui' 
      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'

    