# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webProject: 'src/TaxCalculator.WebApi/TaxCalculator.WebApi.csproj'

steps:

- script: dotnet restore $(webProject)
  displayName: 'dotnet restore'

- script: dotnet build $(webProject) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'  

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: 'malagueta/pensiontools'
    dockerfile: 'src/TaxCalculator.WebApi/Dockerfile'
    containerRegistry: 'kDocker Registery'
    tags: |
      '0.0.1'    