query Calculate(
    $calculationId: UUID!,
    $calculationParameter: CalculationParametersInput!,
    $municipality: MunicipalityInput!,
    $person: CalculationPersonInput!,
    $accountHolder: AccountInput!
    $cashFlowHolder: CashFlowInput!
    $taxActionHolder: TaxActionInput!) {

  calculate(request: {
        calculationId: $calculationId
        
        calculationParameter: $calculationParameter

        person:  $person

        municipality:  $municipality

        accountHolder: $accountHolder
    
        cashFlowHolder: $cashFlowHolder

        taxationActionHolder: $taxActionHolder
    })
    {
        isSuccess
        
        errors

        calculationId

        transactions {
            incomeAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }
            }

            wealthAccounts{
              id
              name
                transactions{
                description
                valutaDate
                amount
                flow
              }
            }

            thirdPillarAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }
            }

            occupationalPensionAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }          
            }

            investmentAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }    
            }

            exogenousAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              } 
            }

            liabilityAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              } 
            }
        }
    }
}