query Calculate(
    $calculationId: UUID!,
    $calculationParameter: CalculationParametersInput!,
    $municipality: MunicipalityInput!,
    $person: CalculationPersonInput!,
    $accountHolder: AccountInput!
    $cashFlowHolder: CashFlowInput!) {

  calculate(request: {
        calculationId: $calculationId
        
        calculationParameter: $calculationParameter

        person:  $person

        municipality:  $municipality

        accountHolder: $accountHolder
    
        cashFlowHolder: $cashFlowHolder

        taxationActionHolder:  {
       
              taxPaymentSourceAccountId: "e00d246d-e518-497a-8629-9adb2f2bbae4"
              taxPaymentTargetAccountId: "b10d246d-e518-497a-8629-9adb2f2bbae3"
              balanceActions: [{
                description: "Tax all wealth"
                kindBeginOfTaxationPeriod: NONE
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2024-12-31"
                taxType: WEALTH
                balanceFactor: 1.0
              },
              {
                description: "Tax all wealth"
                kindBeginOfTaxationPeriod: NONE
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2025-12-31"
                taxType: WEALTH
                balanceFactor: 1.0
              },
              {
                description: "Tax all income"
                kindBeginOfTaxationPeriod: BEGIN_OF_YEAR
                beginOfTaxationPeriod: "2024-01-01"
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2024-12-31"
                taxType: INCOME
                balanceFactor: 1.0
              },
              {
                description: "Tax all income"
                kindBeginOfTaxationPeriod: BEGIN_OF_YEAR
                beginOfTaxationPeriod: "2025-01-01"
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2025-12-31"
                taxType: INCOME
                balanceFactor: 1.0
              },
              {
                description: "Tax capital benefits"
                kindBeginOfTaxationPeriod: BEGIN_OF_YEAR
                beginOfTaxationPeriod: "2026-01-01"
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2026-12-31"
                taxType: CAPITAL_BENEFITS
                balanceFactor: 1.0
              }]
            }
    })
    {
        isSuccess
        
        errors

        calculationId

        transactions {
            incomeAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }
            }

            wealthAccounts{
              id
              name
                transactions{
                description
                valutaDate
                amount
                flow
              }
            }

            thirdPillarAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }
            }

            occupationalPensionAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }          
            }

            investmentAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }    
            }

            exogenousAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              } 
            }

            liabilityAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              } 
            }
        }
    }
}