query Calculate(
    $calculationId: UUID!,
    $calculationParameter: CalculationParametersInput!,
    $municipality: MunicipalityInput!,
    $person: CalculationPersonInput!,
    $accountHolder: AccountInput!) {

  calculate(request: {
        calculationId: $calculationId
        
        calculationParameter: $calculationParameter

        person:  $person

        municipality:  $municipality

        accountHolder: $accountHolder
    
        cashFlowHolder: {
            fixedAmountCashFlows: [
            
            {
            dateOfProcess: "2024-01-01"
            description: "Initialer Saldo"
            amount: 200000
            sourceAccountId: "f10d246d-e518-497a-8629-9adb2f2bbae3"
            targetAccountId: "e00d246d-e518-497a-8629-9adb2f2bbae4"
            taxType: WEALTH,
            taxFlowType: IN_FLOW
          }
          {
            dateOfProcess: "2024-01-01"
            description: "Initialer Saldo"
            amount: 50000
            sourceAccountId: "f10d246d-e518-497a-8629-9adb2f2bbae3"
            targetAccountId: "f00d246d-e518-497a-8629-9adb2f2bbae1"
            taxType: NONE,
            taxFlowType: UNDEFINED
          }
          {
            dateOfProcess: "2024-01-01"
            description: "Initialer Saldo"
            amount: 80000
            sourceAccountId: "f0000000-e518-497a-8629-000000000000"
            targetAccountId: "c0000000-0000-0000-8629-9adb2f2bbae4"
            taxType: WEALTH,
            taxFlowType: IN_FLOW
          }
          {
            dateOfProcess: "2024-01-01"
            description: "Initialer Saldo"
            amount: 150000
            sourceAccountId: "f10d246d-e518-497a-8629-9adb2f2bbae3"
            targetAccountId: "f00d246d-e518-497b-8629-9adb2f2bbae1"
            taxType: NONE,
            taxFlowType: UNDEFINED
          }
          {
            dateOfProcess: "2024-01-01"
            description: "Initialer Saldo"
            amount: 20000
            sourceAccountId: "f10d246d-e518-497a-8629-9adb2f2bbae3"
            targetAccountId: "f00d246d-e518-497a-8629-9adb2f2bbae0"
            taxType: NONE,
            taxFlowType: UNDEFINED
          }
          {
            dateOfProcess: "2024-01-01"
            description: "Lohnzahlung 1"
            amount: 50000
            sourceAccountId: "f00d246d-e518-497a-8629-9adb2f2bbae3"
            targetAccountId: "f00d246d-e518-497a-8629-9adb2f2bbae2"
            taxType: INCOME,
            taxFlowType: IN_FLOW
         }
         {
            dateOfProcess: "2024-07-01"
            description: "Lohnzahlung 2"
            amount: 50000
            sourceAccountId: "f00d246d-e518-497a-8629-9adb2f2bbae3"
            targetAccountId: "f00d246d-e518-497a-8629-9adb2f2bbae2"
            taxType: INCOME,
            taxFlowType: IN_FLOW
         }
         {
            dateOfProcess: "2024-07-01"
            description: "Einkauf"
            amount: 5000
            sourceAccountId: "f00d246d-e518-497a-8629-9adb2f2bbae2"
            targetAccountId: "f00d246d-e518-497a-8629-9adb2f2bbae0"
            taxType: INCOME,
            taxFlowType: OUT_FLOW
         }
            ]
            transferRatioCashFlows: [
            {
                dateOfProcess: "2026-12-31"
                transferFactor: 0.5
                sourceAccountId: "f00d246d-e518-497a-8629-9adb2f2bbae1"
                targetAccountId: "e00d246d-e518-497a-8629-9adb2f2bbae4"
                taxType: CAPITAL_BENEFITS,
                taxFlowType: IN_FLOW
             }]
            balanceGrowthCashFlows: []
        }

        taxationActionHolder:  {
       
              taxPaymentSourceAccountId: "e00d246d-e518-497a-8629-9adb2f2bbae4"
              taxPaymentTargetAccountId: "b10d246d-e518-497a-8629-9adb2f2bbae3"
              balanceActions: [{
                description: "Tax all wealth"
                kindBeginOfTaxationPeriod: NONE
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2024-12-31"
                taxType: WEALTH
                balanceFactor: 1.0
              },
              {
                description: "Tax all wealth"
                kindBeginOfTaxationPeriod: NONE
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2025-12-31"
                taxType: WEALTH
                balanceFactor: 1.0
              },
              {
                description: "Tax all income"
                kindBeginOfTaxationPeriod: BEGIN_OF_YEAR
                beginOfTaxationPeriod: "2024-01-01"
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2024-12-31"
                taxType: INCOME
                balanceFactor: 1.0
              },
              {
                description: "Tax all income"
                kindBeginOfTaxationPeriod: BEGIN_OF_YEAR
                beginOfTaxationPeriod: "2025-01-01"
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2025-12-31"
                taxType: INCOME
                balanceFactor: 1.0
              },
              {
                description: "Tax capital benefits"
                kindBeginOfTaxationPeriod: BEGIN_OF_YEAR
                beginOfTaxationPeriod: "2026-01-01"
                kindEndOfTaxationPeriod: END_OF_YEAR
                endOfTaxationPeriod: "2026-12-31"
                taxType: CAPITAL_BENEFITS
                balanceFactor: 1.0
              }]
            }
    })
    {
        isSuccess
        
        errors

        calculationId

        transactions {
            incomeAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }
            }

            wealthAccounts{
              id
              name
                transactions{
                description
                valutaDate
                amount
                flow
              }
            }

            thirdPillarAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }
            }

            occupationalPensionAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }          
            }

            investmentAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              }    
            }

            exogenousAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              } 
            }

            liabilityAccounts{
              id
              name
              transactions{
                description
                valutaDate
                amount
                flow
              } 
            }
        }
    }
}