schema {
  query: MultiPeriodCashFlowQueries
}

type MultiPeriodCashFlowQueries {
  calculate(request: MultiPeriodCalculationRequestInput!): MultiPeriodCalculationResponse!
}

input MultiPeriodCalculationRequestInput {
  calculationId: UUID!
  calculationParameter: CalculationParametersInput!
  person: CalculationPersonInput!
  municipality: MunicipalityInput!
  accountHolder: AccountInput!
  cashFlowHolder: CashFlowInput!
  taxationActionHolder: TaxActionInput!
}

type MultiPeriodCalculationResponse {
  calculationId: UUID!
  transactions: AccountTransactionResponse
}

input CalculationParametersInput {
  startDate: Date!
  endDate: Date!
}

scalar UUID

input CalculationPersonInput {
  id: UUID!
  name: String
  gender: Gender
  dateOfBirth: Date
  civilStatus: CivilStatus!
  numberOfChildren: Int
  religiousGroupType: ReligiousGroupType!
  partnerReligiousGroupType: ReligiousGroupType
}

input MunicipalityInput {
  municipalityId: Int!
  taxLocationId: Int
  zipCode: String
  city: String
  canton: Canton
}

input AccountInput {
  incomeAccounts: [IncomeAccountInput!]!
  investmentAccounts: [InvestmentAccountInput!]!
  wealthAccounts: [WealthAccountInput!]!
  occupationalPensionAccounts: [OccupationalPensionAccountInput!]!
  thirdPillarAccounts: [ThirdPillarAccountInput!]!
  exogenousAccounts: [ExogenousAccountInput!]!
}

input CashFlowInput {
  fixedAmountCashFlows: [FixedAmountCashFlowInput!]!
  transferRatioCashFlows: [TransferRatioCashFlowInput!]!
  balanceGrowthCashFlows: [BalanceGrowthCashFlowInput!]!
}

input TaxActionInput {
  taxPaymentSourceAccountId: UUID!
  taxPaymentTargetAccountId: UUID!
  balanceActions: [TaxBalanceActionInput!]!
}

type AccountTransactionResponse {
  exogenousAccounts: [AccountTransactionResult!]!
  incomeAccounts: [AccountTransactionResult!]!
  wealthAccounts: [AccountTransactionResult!]!
  investmentAccounts: [AccountTransactionResult!]!
  occupationalPensionAccounts: [AccountTransactionResult!]!
  thirdPillarAccounts: [AccountTransactionResult!]!
  taxAccounts: [AccountTransactionResult!]!
}

input OccupationalPensionAccountInput {
  "Unique account id"
  id: UUID!
  "Account description"
  description: String
}

"Konto bezeichnet Vermögen, dass der Vermögenssteuer unterliegt"
input WealthAccountInput {
  "Unique account id"
  id: UUID!
  "Account description"
  description: String
}

input InvestmentAccountInput {
  "Unique account id"
  id: UUID!
  "Account description"
  description: String
}

input IncomeAccountInput {
  "Unique account id"
  id: UUID!
  "Account description"
  description: String
}

enum Canton {
  UNDEFINED
  AG
  AI
  AR
  BE
  BL
  BS
  FR
  GE
  GL
  GR
  JU
  LU
  NE
  NW
  OW
  SH
  SO
  SG
  SZ
  TI
  TG
  UR
  VD
  VS
  ZG
  ZH
}

enum ReligiousGroupType {
  OTHER
  PROTESTANT
  CATHOLIC
  ROMAN
}

enum CivilStatus {
  UNDEFINED
  SINGLE
  MARRIED
}

enum Gender {
  UNDEFINED
  FEMALE
  MALE
}

"The `Date` scalar represents an ISO-8601 compliant date type."
scalar Date

input ThirdPillarAccountInput {
  "Unique account id"
  id: UUID!
  "Account description"
  description: String
}

input ExogenousAccountInput {
  "Unique account id"
  id: UUID!
  "Account description"
  description: String
}

input FixedAmountCashFlowInput {
  amount: Decimal!
  description: String
  dateOfProcess: Date!
  sequence: Int
  taxType: TaxType!
  taxFlowType: FlowType!
  sourceAccountId: UUID!
  targetAccountId: UUID!
}

input TransferRatioCashFlowInput {
  transferFactor: Decimal!
  description: String
  dateOfProcess: Date!
  sequence: Int
  taxType: TaxType!
  taxFlowType: FlowType!
  sourceAccountId: UUID!
  targetAccountId: UUID!
}

input BalanceGrowthCashFlowInput {
  netReturn: Decimal!
  description: String
  dateOfProcess: Date!
  sequence: Int
  taxType: TaxType!
  taxFlowType: FlowType!
  sourceAccountId: UUID!
  targetAccountId: UUID!
}

input TaxBalanceActionInput {
  description: String
  kindBeginOfTaxationPeriod: ProcessDateKind!
  beginOfTaxationPeriod: Date
  kindEndOfTaxationPeriod: ProcessDateKind!
  endOfTaxationPeriod: Date
  sequence: Int
  balanceFactor: Decimal!
  taxType: TaxType!
}

type AccountTransactionResult {
  id: UUID!
  name: String
  transactions: [AccountTransaction]
}

type AccountTransaction {
  description: String
  valutaDate: DateTime!
  amount: Decimal!
  flow: FlowType!
}

enum ProcessDateKind {
  NONE
  BEGIN_OF_YEAR
  END_OF_YEAR
  CUSTOM
}

enum FlowType {
  UNDEFINED
  IN_FLOW
  OUT_FLOW
}

enum TaxType {
  NONE
  INCOME
  CAPITAL_BENEFITS
  PERSON
  WEALTH
}

"The `Decimal` scalar type represents a decimal floating-point number."
scalar Decimal

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION